/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aquaplus;

import database.konek;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class DataKaryawan extends javax.swing.JFrame {

    private Statement statement;

    /**
     * Creates new form DataKaryawan
     */
    public DataKaryawan() {
        initComponents();
        isitable();
    }

    private void isitable() {
        DefaultTableModel isitable = new DefaultTableModel();
        isitable.addColumn("ID");
        isitable.addColumn("Nama");
        isitable.addColumn("User Name");
        isitable.addColumn("Password");
        isitable.addColumn("Alamat");
        isitable.addColumn("Nmr Telpn");
        isitable.addColumn("Jabatan");
        try {
            statement = konek.getConnection().createStatement();
            String sql = "Select * from karyawan ";
            ResultSet resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                isitable.addRow(new Object[]{
                    resultSet.getString(1),
                    resultSet.getString(2),
                    resultSet.getString(3),
                    resultSet.getString(4),
                    resultSet.getString(5),
                    resultSet.getString(6),
                    resultSet.getString(7),});
            }
            table.setModel(isitable);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnhapus = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        jabatan = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        nmrtlpn = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        datamaster = new javax.swing.JMenu();
        datapelanggan = new javax.swing.JMenuItem();
        datakaryawan = new javax.swing.JMenuItem();
        databarang = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        transaksipenjualan = new javax.swing.JMenuItem();
        transaksipengeluaran = new javax.swing.JMenuItem();
        rekapdata = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();
        laporanpenjualan = new javax.swing.JMenuItem();
        laporanpengeluaran = new javax.swing.JMenuItem();
        laporanpertanggal = new javax.swing.JMenuItem();
        laporanbulanan = new javax.swing.JMenuItem();
        laporantahunan = new javax.swing.JMenuItem();
        about = new javax.swing.JMenu();
        tentangaplikasi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "nama", "username", "password", "alamat", "nmr_tlpn", "jabatan"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        btnhapus.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        btnhapus.setIcon(new javax.swing.ImageIcon("E:\\New folder (2)\\delete1.jpg")); // NOI18N
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnedit.setIcon(new javax.swing.ImageIcon("E:\\New folder (2)\\edit 1.jpg")); // NOI18N
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnsimpan.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        btnsimpan.setIcon(new javax.swing.ImageIcon("E:\\New folder (2)\\Save 1.jpg")); // NOI18N
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        jabatan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Karyawan", "Kasir", "Pemilik", "Admin" }));
        jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabatanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel5.setText("Jabatan");

        nmrtlpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmrtlpnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel8.setText("Nmr Telpn");

        jLabel6.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel6.setText("Alamat");

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\New folder (2)\\karyawan.jpg")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel4.setText("Password");

        jLabel3.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        jLabel3.setText("UserName");

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel2.setText("Nama karyawan");

        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel7.setText("ID Karyawan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(268, 268, 268)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2)))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nmrtlpn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 92, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(nmrtlpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        datamaster.setText("Data Master");
        datamaster.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N

        datapelanggan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        datapelanggan.setText("Data Pelanggan");
        datapelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datapelangganActionPerformed(evt);
            }
        });
        datamaster.add(datapelanggan);

        datakaryawan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        datakaryawan.setText("Data Karyawan");
        datakaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datakaryawanActionPerformed(evt);
            }
        });
        datamaster.add(datakaryawan);

        databarang.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        databarang.setText("Data Barang");
        databarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databarangActionPerformed(evt);
            }
        });
        datamaster.add(databarang);

        jMenuBar1.add(datamaster);

        transaksi.setText("Transaksi");
        transaksi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N

        transaksipenjualan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        transaksipenjualan.setText("Penjualan");
        transaksipenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksipenjualanActionPerformed(evt);
            }
        });
        transaksi.add(transaksipenjualan);

        transaksipengeluaran.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        transaksipengeluaran.setText("Pengeluaran");
        transaksipengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksipengeluaranActionPerformed(evt);
            }
        });
        transaksi.add(transaksipengeluaran);

        rekapdata.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        rekapdata.setText("Rekap Data");
        rekapdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekapdataActionPerformed(evt);
            }
        });
        transaksi.add(rekapdata);

        jMenuBar1.add(transaksi);

        laporan.setText("Laporan");
        laporan.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N

        laporanpenjualan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporanpenjualan.setText("Laporan Penjualan");
        laporanpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanpenjualanActionPerformed(evt);
            }
        });
        laporan.add(laporanpenjualan);

        laporanpengeluaran.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporanpengeluaran.setText("Laporan Pengeluaran");
        laporanpengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanpengeluaranActionPerformed(evt);
            }
        });
        laporan.add(laporanpengeluaran);

        laporanpertanggal.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporanpertanggal.setText("Laporan per Tanggal");
        laporanpertanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanpertanggalActionPerformed(evt);
            }
        });
        laporan.add(laporanpertanggal);

        laporanbulanan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporanbulanan.setText("Laporan Bulanan");
        laporanbulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanbulananActionPerformed(evt);
            }
        });
        laporan.add(laporanbulanan);

        laporantahunan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporantahunan.setText("Laporan Tahunan");
        laporantahunan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporantahunanActionPerformed(evt);
            }
        });
        laporan.add(laporantahunan);

        jMenuBar1.add(laporan);

        about.setText("About");
        about.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N

        tentangaplikasi.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        tentangaplikasi.setText("Tentang Aplikasi");
        tentangaplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tentangaplikasiActionPerformed(evt);
            }
        });
        about.add(tentangaplikasi);

        jMenuBar1.add(about);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nmrtlpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmrtlpnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmrtlpnActionPerformed

    private void jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jabatanActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed

        if (id.getText().equals("") && nama.getText().equals("") && user.getText().equals("") && password.getText().equals("") && alamat.getText().equals("") && nmrtlpn.getText().equals("") && jabatan.getSelectedItem().equals("")) {
            JOptionPane.showConfirmDialog(null, "Masih Ada Data Yang Kosong");
        } else {
            try {
                statement = konek.getConnection().createStatement();
                String sql = "insert into karyawan (id,nama,user,password,alamat,nmrtlpn,jabatan) values ('" + id.getText() + "','" + nama.getText() + "','" + user.getText() + "','" + password.getText() + "','" + alamat.getText() + "','" + nmrtlpn.getText() + "','" + jabatan.getSelectedItem() + "');";
                statement.execute(sql);
                JOptionPane.showMessageDialog(null, "Data Berhasi Disimpan");
               bersih();
            } catch (SQLException e) {
                JOptionPane.showConfirmDialog(null, e);
            }
        }
        isitable();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        try {
            statement = konek.getConnection().createStatement();
            String sql = "delete from karyawan where id = '" + id.getText() + "'";
            statement.execute(sql);
            JOptionPane.showMessageDialog(null, "Terhapus");
            bersih();
            isitable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try {
            statement = konek.getConnection().createStatement();
            String sql = "update karyawan set nama = '" + nama.getText() + "', user = '" + user.getText() + "', password = '" + password.getText() + "', alamat = '" + alamat.getText() + "', nmrtlpn = '" + nmrtlpn.getText() + "', jabatan = '" + jabatan.getSelectedItem() + "' where id = '" + id.getText() + "'";
            statement.execute(sql);
            JOptionPane.showMessageDialog(null, "Berhasi Di Update");
            bersih();
            isitable();
        } catch (SQLException e) {
            Logger.getLogger(DataKaryawan.class.getName()).log(Level.SEVERE, null, e);

        }
    }//GEN-LAST:event_btneditActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        id.setText(table.getModel().getValueAt(row, 0).toString());
        nama.setText(table.getModel().getValueAt(row, 1).toString());
        user.setText(table.getModel().getValueAt(row, 2).toString());
        password.setText(table.getModel().getValueAt(row, 3).toString());
        alamat.setText(table.getModel().getValueAt(row, 4).toString());
        nmrtlpn.setText(table.getModel().getValueAt(row, 5).toString());
        jabatan.setSelectedItem(table.getModel().getValueAt(row, 6).toString());
        btnsimpan.setEnabled(false);
    }//GEN-LAST:event_tableMouseClicked

    private void tentangaplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tentangaplikasiActionPerformed
        // TODO add your handling code here:
        new About().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tentangaplikasiActionPerformed

    private void laporantahunanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporantahunanActionPerformed
        // TODO add your handling code here:
        new LaporanTahunan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporantahunanActionPerformed

    private void laporanbulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanbulananActionPerformed
        // TODO add your handling code here:
        new LaporanBulanan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporanbulananActionPerformed

    private void laporanpertanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanpertanggalActionPerformed
        // TODO add your handling code here:
        new LapPenjualan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporanpertanggalActionPerformed

    private void laporanpengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanpengeluaranActionPerformed
        // TODO add your handling code here:
        new LaporanPengeluaran().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporanpengeluaranActionPerformed

    private void laporanpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanpenjualanActionPerformed
        // TODO add your handling code here:
        new LaporanPenjualan().setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_laporanpenjualanActionPerformed

    private void rekapdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekapdataActionPerformed
        // TODO add your handling code here:
        new Penjualan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rekapdataActionPerformed

    private void transaksipengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksipengeluaranActionPerformed
        // TODO add your handling code here:
        new TransaksiPengeluaran().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transaksipengeluaranActionPerformed

    private void transaksipenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksipenjualanActionPerformed
        // TODO add your handling code here:
        new TransaksiPenjualan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transaksipenjualanActionPerformed

    private void databarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databarangActionPerformed
        // TODO add your handling code here:
        new Barang().setVisible(true);
        this.dispose();
                          
    }//GEN-LAST:event_databarangActionPerformed

    private void datakaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datakaryawanActionPerformed
        // TODO add your handling code here:
        new DataKaryawan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_datakaryawanActionPerformed

    private void datapelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datapelangganActionPerformed
        // TODO add your handling code here:
        new DataPelanggan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_datapelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataKaryawan.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataKaryawan.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataKaryawan.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataKaryawan.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create sdand display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JTextField alamat;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JMenuItem databarang;
    private javax.swing.JMenuItem datakaryawan;
    private javax.swing.JMenu datamaster;
    private javax.swing.JMenuItem datapelanggan;
    public static javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jabatan;
    private javax.swing.JMenu laporan;
    private javax.swing.JMenuItem laporanbulanan;
    private javax.swing.JMenuItem laporanpengeluaran;
    private javax.swing.JMenuItem laporanpenjualan;
    private javax.swing.JMenuItem laporanpertanggal;
    private javax.swing.JMenuItem laporantahunan;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nmrtlpn;
    private javax.swing.JTextField password;
    private javax.swing.JMenuItem rekapdata;
    private javax.swing.JTable table;
    private javax.swing.JMenuItem tentangaplikasi;
    private javax.swing.JMenu transaksi;
    private javax.swing.JMenuItem transaksipengeluaran;
    private javax.swing.JMenuItem transaksipenjualan;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables

private void bersih() {
        id.requestFocus();
        id.setText("");
        nama.setText("");
        user.setText("");
        password.setText("");
        alamat.setText("");
        nmrtlpn.setText("");
        btnsimpan.setEnabled(true);
    }


}
