/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aquaplus;

import database.konek;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class DataPelanggan extends javax.swing.JFrame {

    private Statement statement;

    /**
     * Creates new form DataPelanggan
     */
    public DataPelanggan() {
        initComponents();
        isitable();
    }

      private void isitable() {
        DefaultTableModel isitable = new DefaultTableModel();
        isitable.addColumn("ID");
        isitable.addColumn("Nama");
        isitable.addColumn("Alamat");
        isitable.addColumn("Nomor Tlpn");
        try {
            statement = konek.getConnection().createStatement();
            String sql = "Select * from pelanggan ";
            ResultSet resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                isitable.addRow(new Object[]{
                    resultSet.getString(1),
                    resultSet.getString(2),
                    resultSet.getString(3),
                    resultSet.getString(4),});
            }
            table.setModel(isitable);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nmrtlpn = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        datamaster = new javax.swing.JMenu();
        datapelanggan = new javax.swing.JMenuItem();
        datakaryawan = new javax.swing.JMenuItem();
        databarang = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        transaksipenjualan = new javax.swing.JMenuItem();
        transaksipengeluaran = new javax.swing.JMenuItem();
        rekapdata = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();
        laporanpenjualan = new javax.swing.JMenuItem();
        laporanpengeluaran = new javax.swing.JMenuItem();
        laporanpertanggal = new javax.swing.JMenuItem();
        laporanbulanan = new javax.swing.JMenuItem();
        laporantahunan = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        tentangaplikasi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\New folder (2)\\pelanggan.jpg")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel3.setText("Nama Pelanggan");

        jLabel4.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel4.setText("Alamat");

        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel5.setText("Nomor Tlpn");

        btnSimpan.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        btnSimpan.setIcon(new javax.swing.ImageIcon("E:\\New folder (2)\\Save 1.jpg")); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon("E:\\New folder (2)\\edit 1.jpg")); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        btnHapus.setIcon(new javax.swing.ImageIcon("E:\\New folder (2)\\delete1.jpg")); // NOI18N
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel2.setText("ID Pelanggan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(247, 247, 247))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(alamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(nama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nmrtlpn)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nmrtlpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSimpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        datamaster.setText("Data Master");
        datamaster.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N

        datapelanggan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        datapelanggan.setText("Data Pelanggan");
        datapelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datapelangganActionPerformed(evt);
            }
        });
        datamaster.add(datapelanggan);

        datakaryawan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        datakaryawan.setText("Data Karyawan");
        datakaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datakaryawanActionPerformed(evt);
            }
        });
        datamaster.add(datakaryawan);

        databarang.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        databarang.setText("Data Barang");
        databarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databarangActionPerformed(evt);
            }
        });
        datamaster.add(databarang);

        jMenuBar1.add(datamaster);

        transaksi.setText("Transaksi");
        transaksi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N

        transaksipenjualan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        transaksipenjualan.setText("Penjualan");
        transaksipenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksipenjualanActionPerformed(evt);
            }
        });
        transaksi.add(transaksipenjualan);

        transaksipengeluaran.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        transaksipengeluaran.setText("Pengeluaran");
        transaksipengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksipengeluaranActionPerformed(evt);
            }
        });
        transaksi.add(transaksipengeluaran);

        rekapdata.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        rekapdata.setText("Rekap Data");
        rekapdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekapdataActionPerformed(evt);
            }
        });
        transaksi.add(rekapdata);

        jMenuBar1.add(transaksi);

        laporan.setText("Laporan");
        laporan.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N

        laporanpenjualan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporanpenjualan.setText("Laporan Penjualan");
        laporanpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanpenjualanActionPerformed(evt);
            }
        });
        laporan.add(laporanpenjualan);

        laporanpengeluaran.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporanpengeluaran.setText("Laporan Pengeluaran");
        laporanpengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanpengeluaranActionPerformed(evt);
            }
        });
        laporan.add(laporanpengeluaran);

        laporanpertanggal.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporanpertanggal.setText("Laporan per Tanggal");
        laporanpertanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanpertanggalActionPerformed(evt);
            }
        });
        laporan.add(laporanpertanggal);

        laporanbulanan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporanbulanan.setText("Laporan Bulanan");
        laporanbulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanbulananActionPerformed(evt);
            }
        });
        laporan.add(laporanbulanan);

        laporantahunan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporantahunan.setText("Laporan Tahunan");
        laporantahunan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporantahunanActionPerformed(evt);
            }
        });
        laporan.add(laporantahunan);

        jMenuBar1.add(laporan);

        jMenu4.setText("About");
        jMenu4.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N

        tentangaplikasi.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        tentangaplikasi.setText("Tentang Aplikasi");
        tentangaplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tentangaplikasiActionPerformed(evt);
            }
        });
        jMenu4.add(tentangaplikasi);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed

        if (id.getText().equals("")
                && id.getText().equals("")
                && nama.getText().equals("")
                && alamat.getText().equals("")
                && nmrtlpn.getText().equals("")
            ) {
            JOptionPane.showConfirmDialog(null, "Masih Ada Data Yang Kosong");
            nama.requestFocus();
        } else {
            try {

                statement = konek.getConnection().createStatement();
                String sql = "insert into pelanggan (id,nama,alamat,nmrtlpn) values ('" + id.getText() + "','" + nama.getText() + "','" + alamat.getText() + "','" + nmrtlpn.getText() + "');";
                statement.execute(sql);
                JOptionPane.showMessageDialog(null, "Data Berhasi Disimpan");
                bersih();
            } catch (SQLException e) {
                JOptionPane.showConfirmDialog(null, e);
            }
        }
        isitable();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            statement = konek.getConnection().createStatement();
            String sql = "update pelanggan set nama = '" + nama.getText() + "',alamat = '" + alamat.getText() + "',alamat = '" + alamat.getText() + "', nmrtlpn = '" + nmrtlpn.getText() + "' where id = '" + id.getText() + "'";;
            statement.execute(sql);
            JOptionPane.showMessageDialog(null, "Berhasi Di Update");
            bersih();
            isitable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            statement = konek.getConnection().createStatement();
            String sql = "delete from pelanggan where id = '" + id.getText() + "'";
            statement.execute(sql);
            JOptionPane.showMessageDialog(null, "Terhapus");
            bersih();
            isitable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void datapelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datapelangganActionPerformed
        // TODO add your handling code here:
        new DataPelanggan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_datapelangganActionPerformed

    private void datakaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datakaryawanActionPerformed
        // TODO add your handling code here:
        new DataKaryawan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_datakaryawanActionPerformed

    private void databarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databarangActionPerformed
        // TODO add your handling code here:
        new Barang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_databarangActionPerformed

    private void transaksipenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksipenjualanActionPerformed
        // TODO add your handling code here:
        new TransaksiPenjualan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transaksipenjualanActionPerformed

    private void transaksipengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksipengeluaranActionPerformed
        // TODO add your handling code here:
        new TransaksiPengeluaran().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transaksipengeluaranActionPerformed

    private void rekapdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekapdataActionPerformed
        // TODO add your handling code here:
        new Penjualan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rekapdataActionPerformed

    private void laporanpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanpenjualanActionPerformed
        // TODO add your handling code here:
        new LaporanPenjualan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporanpenjualanActionPerformed

    private void laporanpengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanpengeluaranActionPerformed
        // TODO add your handling code here:
        new LaporanPengeluaran().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporanpengeluaranActionPerformed

    private void laporanpertanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanpertanggalActionPerformed
        // TODO add your handling code here:
        new LapPenjualan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporanpertanggalActionPerformed

    private void laporanbulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanbulananActionPerformed
        // TODO add your handling code here:
        new LaporanBulanan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporanbulananActionPerformed

    private void laporantahunanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporantahunanActionPerformed
        // TODO add your handling code here:
        new LaporanTahunan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporantahunanActionPerformed

    private void tentangaplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tentangaplikasiActionPerformed
        // TODO add your handling code here:
        new About().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_tentangaplikasiActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        id.setText(table.getModel().getValueAt(row, 0).toString());
        nama.setText(table.getModel().getValueAt(row, 1).toString());
        alamat.setText(table.getModel().getValueAt(row, 2).toString());
        nmrtlpn.setText(table.getModel().getValueAt(row, 3).toString());
        btnSimpan.setEnabled(false);
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JMenuItem databarang;
    private javax.swing.JMenuItem datakaryawan;
    private javax.swing.JMenu datamaster;
    private javax.swing.JMenuItem datapelanggan;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu laporan;
    private javax.swing.JMenuItem laporanbulanan;
    private javax.swing.JMenuItem laporanpengeluaran;
    private javax.swing.JMenuItem laporanpenjualan;
    private javax.swing.JMenuItem laporanpertanggal;
    private javax.swing.JMenuItem laporantahunan;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nmrtlpn;
    private javax.swing.JMenuItem rekapdata;
    private javax.swing.JTable table;
    private javax.swing.JMenuItem tentangaplikasi;
    private javax.swing.JMenu transaksi;
    private javax.swing.JMenuItem transaksipengeluaran;
    private javax.swing.JMenuItem transaksipenjualan;
    // End of variables declaration//GEN-END:variables

    private void bersih() {
        id.requestFocus();
        id.setText("");
        nama.setText("");
        alamat.setText("");
        nmrtlpn.setText("");
        btnSimpan.setEnabled(true);
    }
}
