/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aquaplus;

/**
 *
 * @author ASUS
 */
public class LapPenjualan extends javax.swing.JFrame {

    /**
     * Creates new form LapPenjualan
     */
    public LapPenjualan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        report = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        datamaster = new javax.swing.JMenu();
        datapelanggan = new javax.swing.JMenuItem();
        datakaryawan = new javax.swing.JMenuItem();
        databarang = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        transaksipenjualan = new javax.swing.JMenuItem();
        transaksipengeluaran = new javax.swing.JMenuItem();
        rekapdata = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();
        laporanpenjualan = new javax.swing.JMenuItem();
        laporanpengeluaran = new javax.swing.JMenuItem();
        laporanpertanggal = new javax.swing.JMenuItem();
        laporanbulanan = new javax.swing.JMenuItem();
        laporantahunan = new javax.swing.JMenuItem();
        about = new javax.swing.JMenu();
        tentangaplikasi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel1.setText("Laporan per Tanggal");

        tanggal.setFont(new java.awt.Font("Lucida Calligraphy", 0, 15)); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\New folder (2)\\laporan per tanggal.jpg")); // NOI18N

        report.setIcon(new javax.swing.ImageIcon("E:\\New folder (2)\\Report1.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(report, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(report)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        datamaster.setText("Data Master");
        datamaster.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N

        datapelanggan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        datapelanggan.setText("Data Pelanggan");
        datapelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datapelangganActionPerformed(evt);
            }
        });
        datamaster.add(datapelanggan);

        datakaryawan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        datakaryawan.setText("Data Karyawan");
        datakaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datakaryawanActionPerformed(evt);
            }
        });
        datamaster.add(datakaryawan);

        databarang.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        databarang.setText("Data Barang");
        databarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databarangActionPerformed(evt);
            }
        });
        datamaster.add(databarang);

        jMenuBar1.add(datamaster);

        transaksi.setText("Transaksi");
        transaksi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N

        transaksipenjualan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        transaksipenjualan.setText("Penjualan");
        transaksipenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksipenjualanActionPerformed(evt);
            }
        });
        transaksi.add(transaksipenjualan);

        transaksipengeluaran.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        transaksipengeluaran.setText("Pengeluaran");
        transaksipengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksipengeluaranActionPerformed(evt);
            }
        });
        transaksi.add(transaksipengeluaran);

        rekapdata.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        rekapdata.setText("Rekap Data");
        rekapdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekapdataActionPerformed(evt);
            }
        });
        transaksi.add(rekapdata);

        jMenuBar1.add(transaksi);

        laporan.setText("Laporan");
        laporan.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N

        laporanpenjualan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporanpenjualan.setText("Laporan Penjualan");
        laporanpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanpenjualanActionPerformed(evt);
            }
        });
        laporan.add(laporanpenjualan);

        laporanpengeluaran.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporanpengeluaran.setText("Laporan Pengeluaran");
        laporanpengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanpengeluaranActionPerformed(evt);
            }
        });
        laporan.add(laporanpengeluaran);

        laporanpertanggal.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporanpertanggal.setText("Laporan per Tanggal");
        laporanpertanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanpertanggalActionPerformed(evt);
            }
        });
        laporan.add(laporanpertanggal);

        laporanbulanan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporanbulanan.setText("Laporan Bulanan");
        laporanbulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanbulananActionPerformed(evt);
            }
        });
        laporan.add(laporanbulanan);

        laporantahunan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporantahunan.setText("Laporan Tahunan");
        laporantahunan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporantahunanActionPerformed(evt);
            }
        });
        laporan.add(laporantahunan);

        jMenuBar1.add(laporan);

        about.setText("About");
        about.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N

        tentangaplikasi.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        tentangaplikasi.setText("Tentang Aplikasi");
        tentangaplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tentangaplikasiActionPerformed(evt);
            }
        });
        about.add(tentangaplikasi);

        jMenuBar1.add(about);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tentangaplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tentangaplikasiActionPerformed
        // TODO add your handling code here:
        new About().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_tentangaplikasiActionPerformed

    private void laporanpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanpenjualanActionPerformed
        // TODO add your handling code here:
        new LaporanPenjualan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporanpenjualanActionPerformed

    private void laporanpengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanpengeluaranActionPerformed
        // TODO add your handling code here:
        new LaporanPengeluaran().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporanpengeluaranActionPerformed

    private void laporanpertanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanpertanggalActionPerformed
        // TODO add your handling code here:
        new LapPenjualan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporanpertanggalActionPerformed

    private void laporanbulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanbulananActionPerformed
        // TODO add your handling code here:
        new LaporanBulanan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporanbulananActionPerformed

    private void laporantahunanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporantahunanActionPerformed
        // TODO add your handling code here:
        new LaporanTahunan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporantahunanActionPerformed

    private void transaksipenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksipenjualanActionPerformed
        // TODO add your handling code here:
        new TransaksiPenjualan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transaksipenjualanActionPerformed

    private void transaksipengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksipengeluaranActionPerformed
        // TODO add your handling code here:
        new TransaksiPengeluaran().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transaksipengeluaranActionPerformed

    private void rekapdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekapdataActionPerformed
        // TODO add your handling code here:
        new Penjualan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rekapdataActionPerformed

    private void datapelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datapelangganActionPerformed
        // TODO add your handling code here:
        new DataPelanggan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_datapelangganActionPerformed

    private void datakaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datakaryawanActionPerformed
        // TODO add your handling code here:
        new DataKaryawan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_datakaryawanActionPerformed

    private void databarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databarangActionPerformed
        // TODO add your handling code here:
        new Barang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_databarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LapPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LapPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LapPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LapPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LapPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JMenuItem databarang;
    private javax.swing.JMenuItem datakaryawan;
    private javax.swing.JMenu datamaster;
    private javax.swing.JMenuItem datapelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu laporan;
    private javax.swing.JMenuItem laporanbulanan;
    private javax.swing.JMenuItem laporanpengeluaran;
    private javax.swing.JMenuItem laporanpenjualan;
    private javax.swing.JMenuItem laporanpertanggal;
    private javax.swing.JMenuItem laporantahunan;
    private javax.swing.JMenuItem rekapdata;
    private javax.swing.JButton report;
    public static com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JMenuItem tentangaplikasi;
    private javax.swing.JMenu transaksi;
    private javax.swing.JMenuItem transaksipengeluaran;
    private javax.swing.JMenuItem transaksipenjualan;
    // End of variables declaration//GEN-END:variables
}
