/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aquaplus;
import database.konek;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Date;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class Penjualan extends javax.swing.JFrame {
    private DateFormat df = new SimpleDateFormat("yyyy/MM/dd");
    private Statement statement;

    /**
     * Creates new form Penjualan
     */
    public Penjualan() {
        initComponents();
        isitable();
    }
    
     public void isitable() {
        DefaultTableModel isitable = new DefaultTableModel();
        isitable.addColumn("ID");
        isitable.addColumn("Nama Kasir");
        isitable.addColumn("Tanggal");
        isitable.addColumn("Penjualan Pagi");
        isitable.addColumn("Pengeluaran Pagi");
        isitable.addColumn("Total Pengeluaran Pagi");
        isitable.addColumn("Penjualan Malam");
        isitable.addColumn("Pengeluaran Malam");
        isitable.addColumn("Total Pengeluaran Malam");
        isitable.addColumn("Total");
       
        try {
            statement = konek.getConnection().createStatement();
            String sql = "Select * from penjualan ";
            ResultSet resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                isitable.addRow(new Object[]{
                    resultSet.getString(1),
                    resultSet.getString(2),
                    resultSet.getString(3),
                    resultSet.getString(4),
                    resultSet.getString(5),
                    resultSet.getString(6),
                    resultSet.getString(7),
                    resultSet.getString(8),
                    resultSet.getString(9),
                    resultSet.getString(10),});
            }
            table.setModel(isitable);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        penjualanpagi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        penjualanmalam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pengeluaranmalam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnhapus = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        totalpengeluaranmalam = new javax.swing.JLabel();
        txtRp = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        pengeluaranpagi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        totalpengeluaranpagi = new javax.swing.JLabel();
        txtRp1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        txtRp2 = new javax.swing.JLabel();
        namakasir = new javax.swing.JTextField();
        tpm = new javax.swing.JTextField();
        tpp = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        datamaster = new javax.swing.JMenu();
        datapelanggan = new javax.swing.JMenuItem();
        datakaryawan = new javax.swing.JMenuItem();
        databarang = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        transaksipenjualan = new javax.swing.JMenuItem();
        transaksipengeluaran = new javax.swing.JMenuItem();
        rekapdata = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();
        laporanpenjualan = new javax.swing.JMenuItem();
        laporanpengeluaran = new javax.swing.JMenuItem();
        laporanpertanggal = new javax.swing.JMenuItem();
        laporanbulanan = new javax.swing.JMenuItem();
        laporantahunan = new javax.swing.JMenuItem();
        about = new javax.swing.JMenu();
        tentangaplikasi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel1.setText("Penjualan Pagi");

        penjualanpagi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                penjualanpagiKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel2.setText("Penjualan Malam");

        penjualanmalam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                penjualanmalamKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel5.setText("Pengeluaran");

        pengeluaranmalam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pengeluaranmalamKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel3.setText("Total");

        btnhapus.setIcon(new javax.swing.ImageIcon("E:\\New folder (2)\\delete1.jpg")); // NOI18N
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnedit.setIcon(new javax.swing.ImageIcon("E:\\New folder (2)\\edit 1.jpg")); // NOI18N
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnsimpan.setIcon(new javax.swing.ImageIcon("E:\\New folder (2)\\Save 1.jpg")); // NOI18N
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\New folder (2)\\Rekap Data.jpg")); // NOI18N

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel4.setText("id");

        totalpengeluaranmalam.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        totalpengeluaranmalam.setText("0000");
        totalpengeluaranmalam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalpengeluaranmalamKeyReleased(evt);
            }
        });

        txtRp.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        txtRp.setText("Rp");

        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel7.setText("Tgl Pembelian");

        tanggal.setFont(new java.awt.Font("Lucida Calligraphy", 0, 15)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel8.setText("Nama Kasir");

        pengeluaranpagi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pengeluaranpagiKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel11.setText("Pengeluaran");

        jLabel9.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel9.setText("Total");

        totalpengeluaranpagi.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        totalpengeluaranpagi.setText("0000");

        txtRp1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        txtRp1.setText("Rp");

        jLabel12.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel12.setText("Total");

        total.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        total.setText("0000");
        total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalKeyReleased(evt);
            }
        });

        txtRp2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        txtRp2.setText("Rp");

        tpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpmActionPerformed(evt);
            }
        });
        tpm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tpmKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(207, 207, 207))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(namakasir))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel9)
                        .addGap(34, 34, 34)
                        .addComponent(txtRp2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pengeluaranpagi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtRp1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(totalpengeluaranpagi, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(penjualanpagi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addComponent(tpp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(penjualanmalam, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pengeluaranmalam, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tpm, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalpengeluaranmalam, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRp2)
                            .addComponent(namakasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pengeluaranpagi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(totalpengeluaranpagi, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtRp1)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel12)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(penjualanpagi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)))
                        .addGap(4, 4, 4)
                        .addComponent(tpp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(penjualanmalam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(pengeluaranmalam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalpengeluaranmalam, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        datamaster.setText("Data Master");
        datamaster.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N

        datapelanggan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        datapelanggan.setText("Data Pelanggan");
        datapelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datapelangganActionPerformed(evt);
            }
        });
        datamaster.add(datapelanggan);

        datakaryawan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        datakaryawan.setText("Data Karyawan");
        datakaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datakaryawanActionPerformed(evt);
            }
        });
        datamaster.add(datakaryawan);

        databarang.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        databarang.setText("Data Barang");
        databarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databarangActionPerformed(evt);
            }
        });
        datamaster.add(databarang);

        jMenuBar1.add(datamaster);

        transaksi.setText("Transaksi");
        transaksi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N

        transaksipenjualan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        transaksipenjualan.setText("Penjualan");
        transaksipenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksipenjualanActionPerformed(evt);
            }
        });
        transaksi.add(transaksipenjualan);

        transaksipengeluaran.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        transaksipengeluaran.setText("Pengeluaran");
        transaksipengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksipengeluaranActionPerformed(evt);
            }
        });
        transaksi.add(transaksipengeluaran);

        rekapdata.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        rekapdata.setText("Rekap Data");
        rekapdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekapdataActionPerformed(evt);
            }
        });
        transaksi.add(rekapdata);

        jMenuBar1.add(transaksi);

        laporan.setText("Laporan");
        laporan.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N

        laporanpenjualan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporanpenjualan.setText("Laporan Penjualan");
        laporanpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanpenjualanActionPerformed(evt);
            }
        });
        laporan.add(laporanpenjualan);

        laporanpengeluaran.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporanpengeluaran.setText("Laporan Pengeluaran");
        laporanpengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanpengeluaranActionPerformed(evt);
            }
        });
        laporan.add(laporanpengeluaran);

        laporanpertanggal.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporanpertanggal.setText("Laporan per Tanggal");
        laporanpertanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanpertanggalActionPerformed(evt);
            }
        });
        laporan.add(laporanpertanggal);

        laporanbulanan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporanbulanan.setText("Laporan Bulanan");
        laporanbulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanbulananActionPerformed(evt);
            }
        });
        laporan.add(laporanbulanan);

        laporantahunan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporantahunan.setText("Laporan Tahunan");
        laporantahunan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporantahunanActionPerformed(evt);
            }
        });
        laporan.add(laporantahunan);

        jMenuBar1.add(laporan);

        about.setText("About");
        about.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N

        tentangaplikasi.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        tentangaplikasi.setText("Tentang Aplikasi");
        tentangaplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tentangaplikasiActionPerformed(evt);
            }
        });
        about.add(tentangaplikasi);

        jMenuBar1.add(about);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        String fendy = df.format(tanggal.getDate());
        if (namakasir.getText().equals("") 
                && penjualanpagi.getText().equals("") 
                && pengeluaranpagi.getText().equals("") 
                && totalpengeluaranpagi.getText().equals("") 
                && penjualanmalam.getText().equals("") 
                && pengeluaranmalam.getText().equals("") 
                && totalpengeluaranmalam.getText().equals("") 
                && total.getText().equals("")) {
            JOptionPane.showConfirmDialog(null, "Masih Ada Data Yang Kosong");
        } else {
            try {
                statement = konek.getConnection().createStatement();
                String sql = "insert into penjualan (namakasir,tanggal,penjualanpagi,pengeluaranpagi,totalpengeluaranpagi,penjualanmalam,pengeluaranmalam,totalpengeluaranmalam,total) values ('" + namakasir.getText() + "','" + fendy + "','" + penjualanpagi.getText() + "','" + pengeluaranpagi.getText() + "','" + totalpengeluaranpagi.getText() + "','" + penjualanmalam.getText() + "','" + pengeluaranmalam.getText() + "','" + totalpengeluaranmalam.getText() + "','" + total.getText() + "');";
                statement.execute(sql);
                JOptionPane.showMessageDialog(null, "Data Berhasi Disimpan");
                bersih();
               
            } catch (SQLException e) {
                JOptionPane.showConfirmDialog(null, e);
            }
        }
        isitable();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try {
            statement = konek.getConnection().createStatement();
            String sql = "delete from penjualan where id = '" + id.getText() + "'";
            statement.execute(sql);
            JOptionPane.showMessageDialog(null, "Terhapus");
            bersih();
            isitable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        String fendy = df.format(tanggal.getDate());
        try {
            statement = konek.getConnection().createStatement();
            String sql = "update penjualan set namakasir = '" + namakasir.getText() + "', penjualanpagi = '" + penjualanpagi.getText() + "', pengeluaranpagi = '" + pengeluaranpagi.getText() + "', totalpengeluaranpagi = '" + totalpengeluaranpagi.getText() + "', penjualanmalam = '" + penjualanmalam.getText() + "', pengeluaranmalam = '" + pengeluaranmalam.getText() + "', totalpengeluaranmalam = '" + totalpengeluaranmalam.getText() + "', total = '" + total.getText() + "', where id = '" + id.getText() + "'";
            statement.execute(sql);
            JOptionPane.showMessageDialog(null, "Berhasi Di Update");
            bersih();
            isitable();
        } catch (SQLException e) {
           Logger.getLogger(Penjualan.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        try {
            int row = table.getSelectedRow();
            Date tanggals = new SimpleDateFormat("yyyy-MM-dd").parse(table.getModel().getValueAt(row, 2).toString());
            tanggal.setDate(tanggals);
            id.setText(table.getModel().getValueAt(row, 0).toString());
            namakasir.setText(table.getModel().getValueAt(row, 1).toString());
            penjualanpagi.setText(table.getModel().getValueAt(row, 3).toString());
            pengeluaranpagi.setText(table.getModel().getValueAt(row, 4).toString());
            totalpengeluaranpagi.setText(table.getModel().getValueAt(row, 5).toString());
            penjualanmalam.setText(table.getModel().getValueAt(row, 6).toString());
            pengeluaranmalam.setText(table.getModel().getValueAt(row, 7).toString());
            totalpengeluaranmalam.setText(table.getModel().getValueAt(row, 8).toString());
            total.setText(table.getModel().getValueAt(row, 9).toString());
            btnsimpan.setEnabled(false);
            } catch (ParseException ex) {
            Logger.getLogger(Penjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void tentangaplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tentangaplikasiActionPerformed
        // TODO add your handling code here:
        new About().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_tentangaplikasiActionPerformed

    private void laporanpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanpenjualanActionPerformed
        // TODO add your handling code here:
        new LaporanPenjualan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporanpenjualanActionPerformed

    private void laporanpengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanpengeluaranActionPerformed
        // TODO add your handling code here:
        new LaporanPengeluaran().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporanpengeluaranActionPerformed

    private void laporanpertanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanpertanggalActionPerformed
        // TODO add your handling code here:
        new LapPenjualan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporanpertanggalActionPerformed

    private void laporanbulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanbulananActionPerformed
        // TODO add your handling code here:
        new LaporanBulanan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporanbulananActionPerformed

    private void laporantahunanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporantahunanActionPerformed
        // TODO add your handling code here:
        new LaporanTahunan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporantahunanActionPerformed

    private void transaksipenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksipenjualanActionPerformed
        // TODO add your handling code here:
        new TransaksiPenjualan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transaksipenjualanActionPerformed

    private void transaksipengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksipengeluaranActionPerformed
        // TODO add your handling code here:
        new TransaksiPengeluaran().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transaksipengeluaranActionPerformed

    private void rekapdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekapdataActionPerformed
        // TODO add your handling code here:
        new Penjualan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rekapdataActionPerformed

    private void datapelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datapelangganActionPerformed
        // TODO add your handling code here:
        new DataPelanggan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_datapelangganActionPerformed

    private void datakaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datakaryawanActionPerformed
        // TODO add your handling code here:
        new DataKaryawan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_datakaryawanActionPerformed

    private void databarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databarangActionPerformed
        // TODO add your handling code here:
        new Barang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_databarangActionPerformed

    private void penjualanmalamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_penjualanmalamKeyReleased
        // TODO add your handling code here:
          
    }//GEN-LAST:event_penjualanmalamKeyReleased

    private void pengeluaranmalamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pengeluaranmalamKeyReleased
        // TODO add your handling code here:
        if (pengeluaranmalam.getText().isEmpty()) {
        } else { 
                int malam = Integer.valueOf(penjualanmalam.getText());
                int pengeluaran = Integer.valueOf(pengeluaranmalam.getText());
                int totals = malam - pengeluaran ;
                totalpengeluaranmalam.setText("" + totals);
                tpm.setText(""+totals);
                         
        }   
              
    }//GEN-LAST:event_pengeluaranmalamKeyReleased

    private void penjualanpagiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_penjualanpagiKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_penjualanpagiKeyReleased

    private void pengeluaranpagiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pengeluaranpagiKeyReleased
        // TODO add your handling code here:
        if (pengeluaranpagi.getText().isEmpty()) {
        } else { 
                int pagi = Integer.valueOf(penjualanpagi.getText());
                int pengeluaran = Integer.valueOf(pengeluaranpagi.getText());
                int totals = pagi - pengeluaran ;
                totalpengeluaranpagi.setText("" + totals);
                tpp.setText(""+totals);
                         
        }
        
    }//GEN-LAST:event_pengeluaranpagiKeyReleased

    private void totalpengeluaranmalamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalpengeluaranmalamKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_totalpengeluaranmalamKeyReleased

    private void totalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_totalKeyReleased

    private void tpmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpmKeyReleased

        if (tpm.getText().isEmpty()) {
        } else { 
                int pagi = Integer.valueOf(tpp.getText());
                int malam = Integer.valueOf(tpm.getText());
                int totals = pagi + malam ;
                total.setText("" + totals);
        }
    }//GEN-LAST:event_tpmKeyReleased

    private void tpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpmActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JMenuItem databarang;
    private javax.swing.JMenuItem datakaryawan;
    private javax.swing.JMenu datamaster;
    private javax.swing.JMenuItem datapelanggan;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu laporan;
    private javax.swing.JMenuItem laporanbulanan;
    private javax.swing.JMenuItem laporanpengeluaran;
    private javax.swing.JMenuItem laporanpenjualan;
    private javax.swing.JMenuItem laporanpertanggal;
    private javax.swing.JMenuItem laporantahunan;
    private javax.swing.JTextField namakasir;
    private javax.swing.JTextField pengeluaranmalam;
    private javax.swing.JTextField pengeluaranpagi;
    private javax.swing.JTextField penjualanmalam;
    private javax.swing.JTextField penjualanpagi;
    private javax.swing.JMenuItem rekapdata;
    private javax.swing.JTable table;
    public static com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JMenuItem tentangaplikasi;
    private javax.swing.JLabel total;
    private javax.swing.JLabel totalpengeluaranmalam;
    private javax.swing.JLabel totalpengeluaranpagi;
    private javax.swing.JTextField tpm;
    private javax.swing.JTextField tpp;
    private javax.swing.JMenu transaksi;
    private javax.swing.JMenuItem transaksipengeluaran;
    private javax.swing.JMenuItem transaksipenjualan;
    private javax.swing.JLabel txtRp;
    private javax.swing.JLabel txtRp1;
    private javax.swing.JLabel txtRp2;
    // End of variables declaration//GEN-END:variables


private void bersih() {
        namakasir.requestFocus();
        namakasir.setText("");
        penjualanpagi.setText("");
        pengeluaranpagi.setText("");
        totalpengeluaranpagi.setText("0000");
        penjualanmalam.setText("");
        pengeluaranmalam.setText("");
        totalpengeluaranmalam.setText("0000");
        total.setText("0000");
        btnsimpan.setEnabled(true);
    }
}
