/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aquaplus;

import database.konek;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class TransaksiPengeluaran extends javax.swing.JFrame {
    
    private DateFormat df = new SimpleDateFormat("yyyy/MM/dd");

    private Statement statement;

    /**
     * Creates new form TransaksiPengeluaran
     */
    public TransaksiPengeluaran() {
        initComponents();
        isitable();
    }

    private void isitable() {
        DefaultTableModel isitable = new DefaultTableModel();
        isitable.addColumn("Id");
        isitable.addColumn("Kasir");
        isitable.addColumn("Tanggal");
        isitable.addColumn("Pengeluaran");
        isitable.addColumn("Total");
        try {
            statement = konek.getConnection().createStatement();
            String sql = "Select * from transaksipengeluaran ";
            ResultSet resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                isitable.addRow(new Object[]{
                    resultSet.getString(1),
                    resultSet.getString(2),
                    resultSet.getString(3),
                    resultSet.getString(4),
                    resultSet.getString(5),
                });
            }
            table.setModel(isitable);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        total = new javax.swing.JTextField();
        pengeluaran = new javax.swing.JTextField();
        tanggal = new com.toedter.calendar.JDateChooser();
        kasir = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        datamaster = new javax.swing.JMenu();
        datapelanggan = new javax.swing.JMenuItem();
        datakaryawan = new javax.swing.JMenuItem();
        databarang = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        transaksipenjualan = new javax.swing.JMenuItem();
        transaksipengeluaran = new javax.swing.JMenuItem();
        rekapdata = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();
        laporanpenjualan = new javax.swing.JMenuItem();
        laporanpengeluaran = new javax.swing.JMenuItem();
        laporanpertanggal = new javax.swing.JMenuItem();
        laporanbulanan = new javax.swing.JMenuItem();
        laporantahunan = new javax.swing.JMenuItem();
        about = new javax.swing.JMenu();
        tentangaplikasi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        btnsimpan.setIcon(new javax.swing.ImageIcon("E:\\New folder (2)\\Save 1.jpg")); // NOI18N
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnedit.setIcon(new javax.swing.ImageIcon("E:\\New folder (2)\\edit 1.jpg")); // NOI18N
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setIcon(new javax.swing.ImageIcon("E:\\New folder (2)\\delete1.jpg")); // NOI18N
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengeluaranActionPerformed(evt);
            }
        });

        tanggal.setFont(new java.awt.Font("Lucida Calligraphy", 0, 15)); // NOI18N

        jLabel4.setText("Kasir");

        jLabel3.setText("Tanggal");

        jLabel6.setText("Pengeluaran");

        jLabel5.setText("Total");

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\New folder (2)\\pengeluaran.jpg")); // NOI18N

        jLabel2.setText("id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(36, 36, 36))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6)))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kasir)
                                    .addComponent(pengeluaran)
                                    .addComponent(total)
                                    .addComponent(tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(kasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        datamaster.setText("Data Master");
        datamaster.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N

        datapelanggan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        datapelanggan.setText("Data Pelanggan");
        datapelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datapelangganActionPerformed(evt);
            }
        });
        datamaster.add(datapelanggan);

        datakaryawan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        datakaryawan.setText("Data Karyawan");
        datakaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datakaryawanActionPerformed(evt);
            }
        });
        datamaster.add(datakaryawan);

        databarang.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        databarang.setText("Data Barang");
        databarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databarangActionPerformed(evt);
            }
        });
        datamaster.add(databarang);

        jMenuBar1.add(datamaster);

        transaksi.setText("Transaksi");
        transaksi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N

        transaksipenjualan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        transaksipenjualan.setText("Penjualan");
        transaksipenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksipenjualanActionPerformed(evt);
            }
        });
        transaksi.add(transaksipenjualan);

        transaksipengeluaran.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        transaksipengeluaran.setText("Pengeluaran");
        transaksipengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksipengeluaranActionPerformed(evt);
            }
        });
        transaksi.add(transaksipengeluaran);

        rekapdata.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        rekapdata.setText("Rekap Data");
        rekapdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekapdataActionPerformed(evt);
            }
        });
        transaksi.add(rekapdata);

        jMenuBar1.add(transaksi);

        laporan.setText("Laporan");
        laporan.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N

        laporanpenjualan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporanpenjualan.setText("Laporan Penjualan");
        laporanpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanpenjualanActionPerformed(evt);
            }
        });
        laporan.add(laporanpenjualan);

        laporanpengeluaran.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporanpengeluaran.setText("Laporan Pengeluaran");
        laporanpengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanpengeluaranActionPerformed(evt);
            }
        });
        laporan.add(laporanpengeluaran);

        laporanpertanggal.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporanpertanggal.setText("Laporan per Tanggal");
        laporanpertanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanpertanggalActionPerformed(evt);
            }
        });
        laporan.add(laporanpertanggal);

        laporanbulanan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporanbulanan.setText("Laporan Bulanan");
        laporanbulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanbulananActionPerformed(evt);
            }
        });
        laporan.add(laporanbulanan);

        laporantahunan.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        laporantahunan.setText("Laporan Tahunan");
        laporantahunan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporantahunanActionPerformed(evt);
            }
        });
        laporan.add(laporantahunan);

        jMenuBar1.add(laporan);

        about.setText("About");
        about.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N

        tentangaplikasi.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        tentangaplikasi.setText("Tentang Aplikasi");
        tentangaplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tentangaplikasiActionPerformed(evt);
            }
        });
        about.add(tentangaplikasi);

        jMenuBar1.add(about);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        String date = df.format(tanggal.getDate());
        try {
            statement = konek.getConnection().createStatement();
            String sql = "update transaksipengeluaran set kasir = '" + kasir.getText()+ "', tanggal = '" + date + "', pengeluaran = '" + pengeluaran.getText()+ "', total = '" + total.getText()+ "' where id = '" + id.getText() + "'";
            statement.execute(sql);
            JOptionPane.showMessageDialog(null, "Berhasi Di Update");
            bersih();
            isitable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try {
                statement = konek.getConnection().createStatement();
                String sql = "delete from transaksipengeluaran where id = '" + id.getText() + "'";
                statement.execute(sql);
                JOptionPane.showMessageDialog(null, "Terhapus");
                bersih();
                isitable();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        String fendy = df.format(tanggal.getDate());
        if ( kasir.getText().equals("") 
                && equals("") 
                && pengeluaran.getText().equals("") 
                && total.getText().equals("")) {
            JOptionPane.showConfirmDialog(null, "Masih Ada Data Yang Kosong");
        } else {
            try {
                statement = konek.getConnection().createStatement();
                String sql = "insert into transaksipengeluaran (kasir,tanggal,pengeluaran,total) values ('" + kasir.getText()+ "','" + fendy + "','" + pengeluaran.getText() + "','" + total.getText() + "');";
                statement.execute(sql);
                JOptionPane.showMessageDialog(null, "Berhasi Disimpan");
                bersih();
            } catch (SQLException e) {
                JOptionPane.showConfirmDialog(null, e);
            }
        }
        isitable();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        try {
            int row = table.getSelectedRow();
            Date tanggals = new SimpleDateFormat("yyyy-MM-dd").parse(table.getModel().getValueAt(row, 2).toString());
            tanggal.setDate(tanggals);
            id.setText(table.getModel().getValueAt(row, 0).toString());
            kasir.setText(table.getModel().getValueAt(row, 1).toString());
            pengeluaran.setText(table.getModel().getValueAt(row, 3).toString());
            total.setText(table.getModel().getValueAt(row, 4).toString());
            btnsimpan.setEnabled(false);
        } catch (ParseException ex) {
            Logger.getLogger(TransaksiPengeluaran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pengeluaranActionPerformed

    private void tentangaplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tentangaplikasiActionPerformed
        // TODO add your handling code here:
        new About().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_tentangaplikasiActionPerformed

    private void laporanpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanpenjualanActionPerformed
        // TODO add your handling code here:
        new LaporanPenjualan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporanpenjualanActionPerformed

    private void laporanpengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanpengeluaranActionPerformed
        // TODO add your handling code here:
        new LaporanPengeluaran().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporanpengeluaranActionPerformed

    private void laporanpertanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanpertanggalActionPerformed
        // TODO add your handling code here:
        new LapPenjualan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporanpertanggalActionPerformed

    private void laporanbulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanbulananActionPerformed
        // TODO add your handling code here:
        new LaporanBulanan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporanbulananActionPerformed

    private void laporantahunanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporantahunanActionPerformed
        // TODO add your handling code here:
        new LaporanTahunan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporantahunanActionPerformed

    private void datapelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datapelangganActionPerformed
        // TODO add your handling code here:
        new DataPelanggan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_datapelangganActionPerformed

    private void datakaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datakaryawanActionPerformed
        // TODO add your handling code here:
        new DataKaryawan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_datakaryawanActionPerformed

    private void databarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databarangActionPerformed
        // TODO add your handling code here:
        new Barang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_databarangActionPerformed

    private void transaksipenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksipenjualanActionPerformed
        // TODO add your handling code here:
        new TransaksiPenjualan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transaksipenjualanActionPerformed

    private void transaksipengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksipengeluaranActionPerformed
        // TODO add your handling code here:
        new TransaksiPengeluaran().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transaksipengeluaranActionPerformed

    private void rekapdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekapdataActionPerformed
        // TODO add your handling code here:
        new Penjualan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rekapdataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiPengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiPengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiPengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiPengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiPengeluaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JMenuItem databarang;
    private javax.swing.JMenuItem datakaryawan;
    private javax.swing.JMenu datamaster;
    private javax.swing.JMenuItem datapelanggan;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kasir;
    private javax.swing.JMenu laporan;
    private javax.swing.JMenuItem laporanbulanan;
    private javax.swing.JMenuItem laporanpengeluaran;
    private javax.swing.JMenuItem laporanpenjualan;
    private javax.swing.JMenuItem laporanpertanggal;
    private javax.swing.JMenuItem laporantahunan;
    private javax.swing.JTextField pengeluaran;
    private javax.swing.JMenuItem rekapdata;
    private javax.swing.JTable table;
    public static com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JMenuItem tentangaplikasi;
    private javax.swing.JTextField total;
    private javax.swing.JMenu transaksi;
    private javax.swing.JMenuItem transaksipengeluaran;
    private javax.swing.JMenuItem transaksipenjualan;
    // End of variables declaration//GEN-END:variables

private void bersih() {
        kasir.requestFocus();
        kasir.setText("");
        pengeluaran.setText("");
        total.setText("");
        btnsimpan.setEnabled(true);
    }
}
